name: test

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ../../frontend/.github/workflow/workflow
            - name: Build React App
              run: yarn install && yarn run build
